spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo
    username: root
    password: root
logging:
  level:
    root: info
    ch.gatzka: debug
    org.hibernate.orm.connections.pooling: warn
    org.hibernate.engine.transaction.jta.platform.internal.JtaPlatformInitiator: warn